name: Python Checks
on:
  push:
    branches:
      - '*'

jobs:
  install_dependencies:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint ruff black bandit pytype

  pylint_check:
    runs-on: ubuntu-latest
    needs: install_dependencies
    steps:
      - name: Run Pylint
        run: pylint .
        continue-on-error: true

  ruff_check:
    runs-on: ubuntu-latest
    needs: install_dependencies
    steps:
      - name: Run Ruff
        run: ruff .
        continue-on-error: true

  black_check:
    runs-on: ubuntu-latest
    needs: install_dependencies
    steps:
      - name: Run Black
        run: black . --check --diff
        continue-on-error: true

  bandit_check:
    runs-on: ubuntu-latest
    needs: install_dependencies
    steps:
      - name: Run Bandit
        run: bandit .
        continue-on-error: true

  pytype_check:
    runs-on: ubuntu-latest
    needs: install_dependencies
    steps:
      - name: Run Pytype
        run: pytype .
        continue-on-error: true
